config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :links
  resources :regular_links, controller: 'links'
  resources :ephemeral_links, controller: 'links'
  resources :temporary_links, controller: 'links'
  resources :exclusive_links, controller: 'links'
  get "/links/:id/visits", to: "links#visits", as: "visits"

  get "/l/:slug", to: "access#access", as: "access"
  post '/l/protected/:slug', to: 'access#validate_password', as: 'validate_password'

  devise_for :users
  devise_scope :user do
    get "profile" => "devise/sessions#show"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ephemeral_link.rb
class EphemeralLink < Link
  def accessible?
    self.visits.count == 0
  end
end

app/models/exclusive_link.rb
class ExclusiveLink < Link
  validates_presence_of :password
  validates :password , length: {minimum: 6}, if: -> { password.present? }
  before_create :encrypt_password
  before_update :encrypt_password

  def authenticated?(password)
    BCrypt::Password.new(self.password) == password
  end

  private

  def encrypt_password
    self.password = BCrypt::Password.create(password)
  end

end

app/models/link.rb
class Link < ApplicationRecord
  before_validation :remove_trailing_slashes_from_url

  validates_presence_of :url, :type
  validates_uniqueness_of :url, scope: :user_id
  validates :url, format: { with: URI::regexp }, if: -> { url.present? }
  belongs_to :user
  has_many :visits, dependent: :destroy

  before_create :generate_slug

  def time_ago
    seconds_ago = Time.zone.now - created_at
    minutes_ago = (seconds_ago / 60).to_i
    hours_ago = (minutes_ago / 60).to_i
    days_ago = (hours_ago / 24).to_i

    case
      when minutes_ago < 1 then "Hace instantes"
      when hours_ago < 1 then "Hace #{minutes_ago} minutos"
      when days_ago < 1 then "Hace #{hours_ago} horas"
      else "Hace #{days_ago} días"
    end
  end

  def accessible?
    true
  end

  def get_name
    self.name? ? self.name : self.url
  end

  private

  def generate_slug
    self.slug = loop do
      rand = SecureRandom.hex
      generated_slug = Digest::MD5.hexdigest(url + rand)[0..5]
      break generated_slug unless Link.exists?(slug: generated_slug)
    end
  end

  def remove_trailing_slashes_from_url
    self.url = url.gsub(/\/+$/, '')
  end
end

app/models/regular_link.rb
class RegularLink < Link

end

app/models/temporary_link.rb
class TemporaryLink < Link
  validates_presence_of :expiration_date
  validate :expiration_date_in_future, if: -> { expiration_date.present? }

  def accessible?
    Time.now < self.expiration_date
  end

  private

  def expiration_date_in_future
    if self.expiration_date.nil? || self.expiration_date <= Time.now
      errors.add(:expiration_date, "must be in the future")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable


  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9_]+\z/ }, length: { in: 3..20 }

  has_many :links, dependent: :destroy

end

app/models/visit.rb
class Visit < ApplicationRecord
  validates_presence_of :ip

  belongs_to :link

  scope :filter_by_ip, ->(ip) { where(ip: ip) }
  scope :filter_by_start_date, ->(start_date) { where('created_at >= ?', start_date) }
  scope :filter_by_end_date, ->(end_date) { where('created_at <= ?', end_date.to_date.end_of_day) }

end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def access
    @slug = params[:slug]
    link = Link.find_by(slug: @slug)
    if !link.nil? && link.accessible?
      if link.is_a?(ExclusiveLink)
        render 'access/insert_password'
      else
        link.visits.create(ip: request.remote_ip)
        redirect_to link.url, allow_other_host: true
      end
    elsif !link.nil? && link.is_a?(EphemeralLink)
      render file: "#{Rails.root}/public/403.html", layout: false, status: :not_found
    else
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
  end

  def validate_password
    @slug = params[:slug]
    password = params[:password]
    link = Link.find_by(slug: @slug)

    if !link.nil? && link.authenticated?(password)
      link.visits.create(ip: request.remote_ip)
      redirect_to link.url, allow_other_host: true
    else
      redirect_to access_path(slug: @slug), alert: "Wrong password"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configuer_permitted_parameters, if: :devise_controller?

  protected
  def configuer_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy visits]
  before_action :authenticate_user!

  # GET /links or /links.json
  def index
    @links = current_user.links.page(params[:page]).per(3)
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
    @link = @link.becomes(Link)
  end

  # POST /links or /links.json
  def create
    @link = current_user.links.build(link_params)
    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        @link = @link.becomes(Link)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if link_params[:type].present?
          @link = @link.becomes(link_params[:type].constantize)
      end
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        @link = @link.becomes(Link)
        format.html { render :edit , status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def visits
    @visits = @link.visits.page(params[:page]).per(24)
    filter_visits
  end

  private

  def set_link
    @link = Link.find_by(id: params[:id])
    if @link && @link.user != current_user
      flash[:alert] = "You are not the owner of this link"
      redirect_to root_path
    elsif @link.nil?
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
  end

  # Only allow a list of trusted parameters through.
  def link_params
    params.require(:link).permit(:url, :name, :type, :password, :expiration_date)
  end

  def filter_visits
    @visits = @visits.filter_by_ip(params[:ip]) if params[:ip].present?
    @visits = @visits.filter_by_start_date(params[:start_date]) if params[:start_date].present?
    @visits = @visits.filter_by_end_date(params[:end_date]) if params[:end_date].present?
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/access/insert_password.html.erb
<h1>Enter Password</h1>

<%= form_tag(validate_password_path(slug: @slug), method: :post, data: { turbo: false }) do %>
  <%= label_tag :password, "Password" %>
  <%= password_field_tag :password %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/ephemeral_links/_ephemeral_link.html.erb
<%=  render 'links/link', link: link %>
<div class="row justify-content-start px-4">
    <span class="badge p-3 rounded-pill text-bg-warning col-1"> Ephemeral </span>
</div>
<% if !link.accessible? %>
<div class="w-50 mx-auto">
    <hr>
    <div class="text-danger">This link expired</div>
    <hr>
</div>
<% end %>

app/views/exclusive_links/_exclusive_link.html.erb
<%=  render 'links/link', link: link %>
<div class="row justify-content-start px-4">
    <span class="badge p-3 rounded-pill text-bg-danger col-1"> Exclusive </span>
</div>
<div class="w-50 mx-auto">
    <hr>
    <div> This link is protected by password</div>
    <hr>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow ">
  <div class="container-fluid mx-5">
    <a class="navbar-brand" href="<%= root_path %>">
      <img src="/chqto-logo.png" alt="Chqto" width="100" class="rounded">
    </a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
      </ul>
      <div class="d-flex gap-2">
        <a class="btn btn-light" href="#">Sign in</a>
        <a class="btn btn-light" href="#">Sign up</a>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% unless user_signed_in? %>
    <h1> Welcome to Chqto </h1>
    <hr>
    <p class="lead"> The URL shortener App </p>
    <img src="/chqto-logo-bg.png" alt="Chqto" class="rounded mx-auto d-block my-5 shadow">
<% else %>
    <h2> Hello <%= current_user.username %></h2>
    <%= link_to "Create Link", new_link_path, class: "btn btn-light btn-lg shadow my-3" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chqto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'partials/header' %>
    <div class="text-center">
      <p class="notice alert alert-primary"><%= notice %></p>
      <p class="notice alert alert-danger"><%= alert %></p>
    </div>
    <div class="container text-center mt-5">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li class="alert alert-danger small"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "form-label" %>
    <span class="form-text text-muted"><i>(Optional)</i></span>
    <%= form.text_field :name, class: "form-control" %>
  </div>  
  
  <% if link.new_record? %>
  <div class="field mt-3">
    <%= form.label :url, class: "form-label" %>
    <%= form.text_field :url, class: "form-control" %>
  </div>
  <% end %>
  
  <div data-controller="select" data-action="change->select#toggleInput">
    <div class="field mt-3">
      <%= form.label :type, class: "form-label" %>
      <%= form.select :type, [
          ['Regular','RegularLink'],
          ['Ephemeral', 'EphemeralLink'], 
          ['Temporary', 'TemporaryLink'], 
          ['Exclusive', 'ExclusiveLink'], 
        ], 
        { include_blank: 'Select a category' }, 
        class:'form-select' %>
    </div>
    <div id="password" class="field mt-3 hidden" data-select-target="passwordField">
      <% if link.new_record? %>
      <%= form.label :password, class: "form-label" %>
      <% else %>
        <% if link.class=="ExclusiveLink" %>
        <%= form.label "Change password", class: "form-label"  %>
        <span class="form-text text-muted"><i>(Leave blank to keep)</i></span>
        <% else %>
        <%= form.label "Set password", class: "form-label"  %>
        <% end %>
      <% end %>
      <%= form.password_field :password, class: "form-control"%>

    </div>

    <div id="expiration_date" class="field mt-3 hidden" data-select-target="expirationDateField">
      <%= form.label :expiration_date, class: "form-label" %>
      <%= form.datetime_field :expiration_date, class: "form-control" %>
    </div>
  
  </div>

  <div class="mt-3 py-3">
    <%= form.submit "Save", class: "btn btn-success shadow" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>" class="p-3">
    <% if link.name !="" && link.name!=nil %>
      <div class="bg-light">
        <hr>
        <div><%= link.name %></div>
        <hr>
      </div>
    <% end %>
    <div class="d-flex w-100 justify-content-between">
      <h5>Url: <%= link.url %></h5>
      <h5>
        Chqto: <a href="<%= access_url(link.slug) %>" target="_blank"> <%= access_url(link.slug) %></a>
      </h5>
      <p><%= link.time_ago %></p>
    </div>
</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>
<div class="card p-3 shadow-sm w-75 mx-auto">
  <%= render "form", link: @link %>
  <br>
</div>
<div class="btn-group my-3">
  <%= link_to "Show this link", @link, class:" btn btn-light shadow" %>
  <%= link_to "Back to links", links_path, class: " btn btn-light shadow" %>
</div>

app/views/links/index.html.erb
<h1>Your Links</h1>
<hr class=" mb-3"/>
<div class="text-center my-3" >
  <%= link_to "New link", new_link_path, class:"btn btn-success shadow"%>
</div>
<div class="list-group mt-3 shadow-sm" id="links">
  <% @links.each do |link| %>
    <div class="list-group-item">
      <%= render link, link:link %>
      <p>
        <%= link_to "Show this link", link, class:" btn btn-light shadow-sm" %>
      </p>
    </div>
  <% end %>
</div>
<%= paginate @links %>

app/views/links/new.html.erb
<h1>New link</h1>
<div class="card p-3 shadow-sm w-75 mx-auto">
  <%= render "form", link: @link %>
</div>

app/views/links/show.html.erb
<div class="card shadow-sm p-3">
    <%= render @link, link: @link %>

    <div class="w-50 mx-auto mt-5"  role="group" >
      <div class="btn-group mb-4">
        <%= link_to "Edit this link", edit_link_path(@link), class:"btn btn-outline-success"%>
        <%= link_to "Show Visits", visits_path(@link), class:"btn btn-outline-secondary"  %>
      </div>
      <%= button_to "Destroy this link", @link, method: :delete, class:"mx-3 btn btn-danger mb-2", data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }  %>
    </div>
    <hr>
    <h5> Link Visits </h5>
    <%= line_chart @link.visits.group_by_day(:created_at).count %>
    
</div>
<%= link_to "Back to links", links_path, class:" btn btn-light-sm my-3 shadow" %>

app/views/links/visits.html.erb
<h3>Link Visits</h3>
<h6><%= @link.get_name %></h6>
<div class="card m-3 p-3 shadow-sm align-items-center">
    <%= form_tag(visits_path, method: :get, class: "row gy-2 gx-3 align-items-center") do %>
    <div class="col-auto">
        <%= label_tag :ip, "Filter by IP:" %>
        <%= text_field_tag :ip, params[:ip], class: "form-control" %>
    </div>

    <div class="col-auto">
        <%= label_tag :start_date, "Filter by Start Date:"  %>
        <%= date_field_tag :start_date, params[:start_date], class: "form-control" %>
    </div>

    <div class="col-auto">
        <%= label_tag :end_date, "Filter by End Date:" %>
        <%= date_field_tag :end_date, params[:end_date], class: "form-control" %>
    </div>
    <div class="col-auto">
        <%= submit_tag "Filter", class: "btn btn-primary" %>
    </div>
    <% end %>
</div>
<div class="row">
  <% if @visits.any? && @visits.size > 8 %>
    <% @visits.each_slice(8) do |visits_slice| %>
      <div class="col-md-4 card mx-auto ">
        <table class="table">
          <thead>
            <tr>
              <th>IP</th>
              <th>Day</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
            <% visits_slice.each do |visit| %>
              <tr>
                <td><%= visit.ip %></td>
                <td><%= visit.created_at.to_formatted_s(:day) %></td>
                <td><%= visit.created_at.to_formatted_s(:hour) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  <% elsif @visits.any? %>
    <div class="card w-50 mx-auto">
        <table class="table">
          <thead>
            <tr>
              <th>IP</th>
              <th>Day</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
            <% @visits.each do |visit| %>
            <tr>
                <td><%= visit.ip %></td>
                <td><%= visit.created_at.to_formatted_s(:day) %></td>
                <td><%= visit.created_at.to_formatted_s(:hour) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  <% else %>
    <p>No visits</p>
  <% end %>
</div>

<%= paginate @visits %>

<%= link_to "Back to link", @link, class:" btn btn-light-sm my-3 shadow" %>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow ">
  <div class="container-fluid mx-5">
    <a class="navbar-brand" href="<%= root_path %>">
      <img src="/chqto-logo.png" alt="Chqto" width="100" class="rounded">
    </a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% unless user_signed_in? %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <div class="d-flex gap-2">
        <%= link_to 'Sign Up', new_user_registration_path, :class => 'btn btn-light' %>
        <%= link_to 'Log In', new_user_session_path, :class => 'btn btn-light' %>
      </div>
      <% else %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Your Links', links_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Link', new_link_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Profile', profile_path, :class => 'nav-link' %>
        </li>
      </ul>
      <div class="d-flex gap-2">
        <%= button_to 'Log Out', destroy_user_session_path, :method => :delete, :class => 'btn btn-light' %>

      </div>
      
      <% end %>
    </div>
  </div>
</nav>

app/views/regular_links/_regular_link.html.erb
<%=  render 'links/link', link: link %>
<div class="row justify-content-start px-4">
    <span class="badge p-3 rounded-pill text-bg-primary col-1"> Regular </span>
</div>

app/views/temporary_links/_temporary_link.html.erb
<%=  render 'links/link', link: link %>
<div class="row justify-content-start px-4">
    <span class="badge p-3 rounded-pill text-bg-success col-1"> Temporary </span>
</div>
<div class="w-50 mx-auto">
    <hr>
    <% if link.accessible? %>
    <div>This link expires: <%= link.expiration_date.to_formatted_s(:day)%> at <%= link.expiration_date.to_formatted_s(:hour)%></div>
    <% else %>
    <div class="text-danger">This link expired</div>
    <% end %>
    <hr>
</div>